### ISSUE TITLE
Ignore pycache (and virtualenv?) dirs

### ISSUE THREAD

**Issue by aded** [bm-eugis/frontex-oceanographic-services-api#2]
We have created a virtualenv for deploying the code in the `venv` dir, i.e.:
```
virtualenv -p python3 venv
```
before
```
pip install -r requirements.txt
```
Please could you kindly "git ignore" this dir (`venv`) for us :-)?
Also, a `__pycache__` dir is created, and can be safely ignored.

**Comment by asensioj** [comment]
Done
